### ISSUE TITLE
Build issue with kotlin

### ISSUE THREAD

**Issue by rictic** [codemirror/google-modes#260]
Looks like rollup v0.65.2 fails to parse `kotlin.mode.js`

```
$ node --version
v12.4.0
$ npm --version
6.9.0
$ npx rollup --version
rollup v0.65.2
$ npm run build-kotlin

> google_modes@1.0.0 build-kotlin /Users/rictic/open/google-modes
> grammar-mode --es-module src/kotlin.grammar --output src/kotlin.mode.js && rollup -c rollup.config.js src/kotlin.js -o dist/kotlin.js


src/kotlin.js → dist/kotlin.js...
[!] (buble plugin) SyntaxError: Unterminated regular expression (1:151)
src/kotlin.mode.js (1:151)
]+/, /^for(?![a-zA-Z¡-￿_0-9])/, /^while(?![a-zA-Z¡-￿_0-9])/, /^do(?![a-zA-Z¡-￿_0-9])/, /^in(?![a-zA-Z¡-￿_0-9])/, /^class(?![a-zA-Z¡-￿_0-9])/, /^interface(?![a-zA-Z¡-￿_0-9])/, /^fun(?![a-zA-Z¡-￿_0-9])/, /^typealias(?![a-zA-Z¡-￿_0-9])/, /^(?:[a-zA-Z¡-￿_][a-zA-Z¡-￿_0-9]*|\`(?:(?!\`).)+\`)\@/, /^(?:\.\.|\?\:|[\+\-\*\/\%\<\>]\=?|[\!\=]\=\=?|\=|\&\&|\|\|)/, /^is(?![a-zA-Z¡-￿_0-9])/, [1, "\n", "\t", " "], /^[a-zA-Z0-9¡-￿_\.]+/, /^\@[a-zA-Z0-9¡-￿_]+/, [0, /^(?!\*\/|\{?\@[a-zA-Z0-9¡-￿_])/, /^[^]/], /^(?:enum|sealed|annotation|data|inner|override|lateinit|public|private|internal|protected|tailred|operator|infix|inline|external|extend|const|abstract|final|open|vararg|noinline|crossinline|reified|expect|actual)(?![a-zA-Z¡-￿_0-9])/, /^object(?![a-zA-Z¡-￿_0-9])/, /^(?:val|var)(?![a-zA-Z¡-￿_0-9])/, /^where(?![a-zA-Z¡-￿_0-9])/, /^(?:true|false|null)(?![a-zA-Z¡-￿_0-9])/, /^(?:(?:0x|0X)[0-9_a-fA-F]+|(?:0b|0B)[01_]+|(?:[0-9][0-9_]*(?:\.[0-9_]*)?|\.[0-9_]+)(?:[eE][\+\-]?[0-9_]+)?)[uU]?L?/, /^\'(?:\\.(?:(?!\').)*|.)\'/, /^this(?![a-zA-Z¡-￿_0-9])/, /^it(?![a-zA-Z¡-￿_0-9])/, /^super(?![a-zA-Z¡-￿_0-9])/, /^if(?![a-zA-Z¡-￿_0-9])/, /^when(?![a-zA-Z¡-￿_0-9])/, /^try(?![a-zA-Z¡-￿_0-9])/, /^throw(?![a-zA-Z¡-￿_0-9])/, /^return(?![a-zA-Z¡-￿_0-9])/, /^(?:break|continue)(?![a-zA-Z¡-￿_0-9])/, /^(?:[a-zA-Z¡-￿_][a-zA-Z¡-￿_0-9]*|\`(?:(?!\`).)+\`)(?= *[\(\{])/, /^else(?![a-zA-Z¡-￿_0-9])/, /^dynamic(?![a-zA-Z¡-￿_0-9])/, /^by(?![a-zA-Z¡-￿_0-9])/, /^constructor(?![a-zA-Z¡-￿_0-9])/, /^catch(?![a-zA-Z¡-￿_0-9])/, /^finally(?![a-zA-Z¡-￿_0-9])/, /^(?:in|out)(?![a-zA-Z¡-￿_0-9])/, /^companion(?![a-zA-Z¡-￿_0-9])/, /^init(?![a-zA-Z¡-￿_0-9])/]
                                                                                                                                                           ^
SyntaxError: Unterminated regular expression (1:151)
    at Object.pp$4.raise (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:2827:15)
    at Object.pp$9.readRegexp (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4574:38)
    at Object.pp$9.readToken_slash (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4410:53)
    at Object.pp$9.getTokenFromCode (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4536:19)
    at Object.pp$9.readToken (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4288:17)
    at Object.readToken (/Users/rictic/open/google-modes/node_modules/acorn-jsx/index.js:422:20)
    at Object.pp$9.nextToken (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4279:17)
    at Object.pp$9.next (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:4236:10)
    at Object.pp.eat (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:618:12)
    at Object.pp.expect (/Users/rictic/open/google-modes/node_modules/acorn/dist/acorn.js:682:10)
```

**Comment by marijnh** [comment]
Try again with codemirror-grammar-mode 0.1.9 (I fixed something locally but forgot to cut a release)

**Comment by rictic** [comment]
That fixed it, thanks!
